FROM ubuntu:22.04

LABEL Purpuse=NetAnalysis

RUN apt-get update &&  \
    apt-get install -y iproute2 && \
    apt-get install -y iptables && \
    apt-get install -y nmap

# Keeps the container alive
CMD ["tail", "-f", "/dev/null"]