__all__ = (
    "LaptopUpdate",
    "LaptopCreate",
    "LaptopPreviewModelWithID",
    "LaptopUpdatePartial",
    "LaptopDetail",
    "LaptopPreview",
    "LaptopBase",
    "LaptopFullModel",
    "MonitorBase",
    "MonitorPreviewWithID",
    "MonitorCreate",
    "MonitorPreview",
    "MonitorFullModel",
    "MonitorUpdate",
    "MonitorUpdatePartial",
    "MonitorDetail",
    "DesktopPCUpdate",
    "DesktopPCCreate",
    "DesktopPCPreviewModelWithID",
    "DesktopPCFullModel",
    "DesktopPCUpdatePartial",
    "DesktopPCDetail",
    "DesktopPCBase",
    "DesktopPCUpdatePartial",
)

from core.schemas.items.laptop import (
    LaptopUpdate,
    LaptopCreate,
    LaptopPreviewModelWithID,
    LaptopUpdatePartial,
    LaptopDetail,
    LaptopPreview,
    LaptopBase,
    LaptopFullModel,
)
from core.schemas.items.monitors import (
    MonitorBase,
    MonitorPreviewWithID,
    MonitorCreate,
    MonitorPreview,
    MonitorFullModel,
    MonitorUpdate,
    MonitorUpdatePartial,
    MonitorDetail,
)
from core.schemas.items.desktop_pc import (
    DesktopPCUpdate,
    DesktopPCCreate,
    DesktopPCPreviewModelWithID,
    DesktopPCFullModel,
    DesktopPCUpdatePartial,
    DesktopPCDetail,
    DesktopPCBase,
    DesktopPCUpdatePartial,
)
