"""create laptop model

Revision ID: 54e5bb89802b
Revises: bd4dc9adfbe1
Create Date: 2025-01-02 05:23:42.980868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54e5bb89802b"
down_revision: Union[str, None] = "bd4dc9adfbe1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "laptops",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("screen_frequency", sa.String(), nullable=False),
        sa.Column("diagonal", sa.String(), nullable=False),
        sa.Column("resolution", sa.String(), nullable=False),
        sa.Column("screen_type", sa.String(), nullable=False),
        sa.Column("cpu_model", sa.String(), nullable=False),
        sa.Column("cpu_class", sa.String(), nullable=False),
        sa.Column("cpu_frequency", sa.String(), nullable=False),
        sa.Column("gpu_model", sa.String(), nullable=False),
        sa.Column("gpu_memory", sa.String(), nullable=False),
        sa.Column("ram_size", sa.String(), nullable=False),
        sa.Column("ram_type", sa.String(), nullable=False),
        sa.Column("ram_frequency", sa.String(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("maker", sa.String(), nullable=False),
        sa.Column("storage_size", sa.String(), nullable=False),
        sa.Column("installed_os", sa.String(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("image", sa.String(), nullable=False),
        sa.Column("extra_image", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_laptops_created_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_laptops")),
    )
    op.create_index(
        op.f("ix_laptops_created_at"), "laptops", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_laptops_created_at"), table_name="laptops")
    op.drop_table("laptops")
    # ### end Alembic commands ###
